//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Junto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbUsuario
    {
        public long idUsuario { get; set; }
        public string strMatricula { get; set; }
        public string strNome { get; set; }
        public string strEmail { get; set; }
        public string strSenha { get; set; }
        public string strToken { get; set; }
        public Nullable<System.DateTime> dtCadastro { get; set; }
        public Nullable<System.DateTime> dtGeracaoToken { get; set; }
    }
}
